version: '3.8'

services:
  urlshortener:
    image: api.urling.io:latest
    restart: always
    ports:
      - 9808:9808
    depends_on:
      - redis
    environment:
      GIN_MODE: release
      REDIS_ADDRESS: 127.0.0.1:6379
    network_mode: "host"
  redis:
    image: redis:7.0.4
    restart: always
    ports:
      - 6379:6379
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local