version: '3.8'

services:
  urlshortener:
    image: registry.digitalocean.com/kriekon-01/api.urling.io:latest
    restart: always
    ports:
      - 9808:9808
    depends_on:
      - redis
    environment:
      GIN_MODE: release
      REDIS_ADDRESS: cache:6379
  redis:
    container_name: cache
    image: redis:7.0.4
    restart: always
    ports:
      - 6379
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local